-- pilot lot insert v1 (idempotent via NOT EXISTS on question text)
INSERT INTO public.questions (
  theme, difficulty, question, choices, correct_index, explanation, is_active, status, concept_key, editor_notes
)
SELECT * FROM (VALUES
(
      'vocabulaire'::public.question_theme,
      'facile'::public.question_difficulty,
      'Dans le groupe : « Askip il l’a ghost depuis samedi. » Askip, c’est…',
      '["Apparemment / à ce qu’il paraît","Une appli de notes","Un filtre Snapchat","Un code Wi-Fi"]'::jsonb,
      0,
      'Askip = abréviation de « à ce qu’il paraît ».',
      true,
      'live'::public.question_status,
      'askip',
      'Pilot Askip — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'moyen'::public.question_difficulty,
      'Quel message sonne juste avec « askip » ?',
      '["Askip le concert est annulé, je vérifie encore.","J’ai activé askip dans les réglages.","Askip est une banque.","Askip = antivirus."]'::jsonb,
      0,
      'On rapporte une info non confirmée, pas un outil.',
      true,
      'live'::public.question_status,
      'askip',
      'Pilot Askip — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'facile'::public.question_difficulty,
      'Ton ado : « Wallah j’ai rien touché. » Il veut surtout…',
      '["Insister / jurer que c’est vrai","Parler d’une appli bancaire","Donner un code PIN","Demander le Wi-Fi"]'::jsonb,
      0,
      'Wallah = serment / « je te jure » (variante orale : walpa).',
      true,
      'live'::public.question_status,
      'wallah',
      'Pilot Wallah — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'moyen'::public.question_difficulty,
      'Quel usage colle avec « wallah » ?',
      '["Wallah c’était pas moi qui ai liké ça.","J’ai mis wallah en 5G.","Wallah est un forfait mobile.","Wallah = mode avion."]'::jsonb,
      0,
      'C’est une affirmation orale, pas un réglage.',
      true,
      'live'::public.question_status,
      'wallah',
      'Pilot Wallah — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'facile'::public.question_difficulty,
      'Tu demandes « Tu viens ? » — réponse : « Jsp. » Ça veut dire…',
      '["Je ne sais pas","Je suis prêt","Juste sans problème","Jour sans pub"]'::jsonb,
      0,
      'Jsp = je sais pas (SMS / Snap).',
      true,
      'live'::public.question_status,
      'jsp',
      'Pilot Jsp — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'moyen'::public.question_difficulty,
      'Quel message sonne naturel ?',
      '["À quelle heure on se voit ? — Jsp encore.","Active jsp dans le Bluetooth.","Jsp est une cryptomonnaie.","Jsp = code barre."]'::jsonb,
      0,
      'Réponse d’incertitude, pas un produit.',
      true,
      'live'::public.question_status,
      'jsp',
      'Pilot Jsp — authenticity scene check required before live.'
    ),
(
      'relations_lifestyle'::public.question_theme,
      'moyen'::public.question_difficulty,
      '« Ce mec est un charo. » On parle surtout de quelqu’un qui…',
      '["Enchaîne les conquêtes / est trop « chasse »","Répare des voitures","Gère le Wi-Fi du lycée","Est DJ professionnel"]'::jsonb,
      0,
      'Charo vient de « charognard » : trop focalisé sur les plans / conquêtes.',
      true,
      'live'::public.question_status,
      'charo',
      'Pilot Charo — authenticity scene check required before live.'
    ),
(
      'relations_lifestyle'::public.question_theme,
      'facile'::public.question_difficulty,
      'Quel usage colle avec « charo » ?',
      '["Il DM toutes les stories : gros charo.","J’ai installé charo sur mon téléphone.","Charo est un forfait.","Charo = 5G."]'::jsonb,
      0,
      'Jugement social / relationnel, pas une appli.',
      true,
      'live'::public.question_status,
      'charo',
      'Pilot Charo — authenticity scene check required before live.'
    ),
(
      'culture_pop'::public.question_theme,
      'facile'::public.question_difficulty,
      '« Son discours était trop cringe. » Ça veut dire…',
      '["Gênant / malaisant","Très drôle au second degré","Techniquement parfait","Trop court"]'::jsonb,
      0,
      'Cringe = malaise / gêne — anglicisme très utilisé en France.',
      true,
      'live'::public.question_status,
      'cringe',
      'Pilot Cringe — authenticity scene check required before live.'
    ),
(
      'culture_pop'::public.question_theme,
      'moyen'::public.question_difficulty,
      'Quel message sonne juste ?',
      '["Il a fait un discours devant toute la famille… cringe total.","J’ai activé cringe dans les réglages.","Cringe est une banque.","Cringe = antivirus."]'::jsonb,
      0,
      'On juge une vibe sociale, pas un outil.',
      true,
      'live'::public.question_status,
      'cringe',
      'Pilot Cringe — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'moyen'::public.question_difficulty,
      '« J’ai perdu mon tel, j’suis dans la sauce. » Là, sauce = …',
      '["Dans la galère / embêté","En train de cuisiner","En mode avion","Sur un forfait illimité"]'::jsonb,
      0,
      '« Dans la sauce » = dans la merde / galère. (Autre sens : « saucé » = sous le charme.)',
      true,
      'live'::public.question_status,
      'sauce',
      'Pilot Sauce — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'facile'::public.question_difficulty,
      '« Il est saucé sur elle. » Ça veut plutôt dire…',
      '["Il est sous le charme / trop attiré","Il a mangé trop épicé","Il a un virus","Il a coupé le Wi-Fi"]'::jsonb,
      0,
      'Être saucé = être captivé / en crush fort.',
      true,
      'live'::public.question_status,
      'sauce',
      'Pilot Sauce — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'facile'::public.question_difficulty,
      '« Il a parlé trop fort au resto : c’est la gênance. » Ça décrit…',
      '["Une situation très gênante / un malaise","Une promo restaurant","Un bug de téléphone","Une note sur 20"]'::jsonb,
      0,
      'La gênance = le malaise collectif face à une scène awkward.',
      true,
      'live'::public.question_status,
      'genance',
      'Pilot Gênance — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'moyen'::public.question_difficulty,
      'Quel usage sonne naturel ?',
      '["Il a appelé sa mère en haut-parleur dans le métro… grosse gênance.","J’ai activé gênance en Bluetooth.","Gênance est une appli bancaire.","Gênance = code Wi-Fi."]'::jsonb,
      0,
      'C’est un jugement de situation, pas un réglage.',
      true,
      'live'::public.question_status,
      'genance',
      'Pilot Gênance — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'facile'::public.question_difficulty,
      '« J’ai charbonné tout le week-end pour réviser. » Ça veut dire…',
      '["Travailler / enchaîner dur","Allumer un barbecue","Scroller sans but","Couper les notifs"]'::jsonb,
      0,
      'Charbonner = travailler beaucoup (études, job, projets).',
      true,
      'live'::public.question_status,
      'charbonner',
      'Pilot Charbonner — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'moyen'::public.question_difficulty,
      'Quel message colle ?',
      '["Là je charbonne jusqu’à vendredi, on se voit après.","J’ai installé charbonner.","Charbonner est un forfait.","Charbonner = 5G."]'::jsonb,
      0,
      'Verbe d’effort, pas un produit.',
      true,
      'live'::public.question_status,
      'charbonner',
      'Pilot Charbonner — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'facile'::public.question_difficulty,
      '« Mon daron est pas content. » Daron, c’est…',
      '["Le père (daronne = la mère)","Le professeur principal","Le Wi-Fi de la maison","Le compte Netflix"]'::jsonb,
      0,
      'Daron / daronne = parents, en argot FR.',
      true,
      'live'::public.question_status,
      'daron',
      'Pilot Daron — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'moyen'::public.question_difficulty,
      '« Les darons sont rentrés. » Ça signifie…',
      '["Les parents sont rentrés","Les voisins ont sonné","Le colis est arrivé","La batterie est à 100 %"]'::jsonb,
      0,
      'Les darons = papa et/ou maman.',
      true,
      'live'::public.question_status,
      'daron',
      'Pilot Daron — authenticity scene check required before live.'
    ),
(
      'relations_lifestyle'::public.question_theme,
      'facile'::public.question_difficulty,
      '« T’as vu le nouveau ? Il est bg. » BG veut dire…',
      '["Beau gosse / stylé / attirant","Bon grade scolaire","Batterie faible","Bloc-notes Google"]'::jsonb,
      0,
      'BG = beau gosse.',
      true,
      'live'::public.question_status,
      'bg',
      'Pilot BG — authenticity scene check required before live.'
    ),
(
      'relations_lifestyle'::public.question_theme,
      'moyen'::public.question_difficulty,
      'Quel usage sonne juste ?',
      '["Avec cette coupe, t’es trop bg.","J’ai activé BG dans les réglages.","BG est une banque.","BG = antivirus."]'::jsonb,
      0,
      'Compliment d’apparence / vibe, pas un outil.',
      true,
      'live'::public.question_status,
      'bg',
      'Pilot BG — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'facile'::public.question_difficulty,
      '« Arrête, t’es relou. » Relou veut dire…',
      '["Lourd / agaçant / pénible","Très drôle","Trop discret","En retard"]'::jsonb,
      0,
      'Relou = verlan de « lourd ».',
      true,
      'live'::public.question_status,
      'relou',
      'Pilot Relou — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'moyen'::public.question_difficulty,
      'Quel message colle ?',
      '["Il relance 10 fois : trop relou.","J’ai mis relou en 5G.","Relou est un forfait.","Relou = mode avion."]'::jsonb,
      0,
      'Jugement sur un comportement agaçant.',
      true,
      'live'::public.question_status,
      'relou',
      'Pilot Relou — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'moyen'::public.question_difficulty,
      '« Vas-y y’a pas H, on y va. » Ça veut dire…',
      '["Y’a pas de souci / c’est clair","Y’a pas d’hôtel","Y’a pas de Wi-Fi","Y’a pas d’heure"]'::jsonb,
      0,
      'Y’a pas H ≈ y’a pas de H(istoire) / pas de problème — go.',
      true,
      'live'::public.question_status,
      'ya_pas_h',
      'Pilot Y’a pas H — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'facile'::public.question_difficulty,
      'Quel usage sonne naturel ?',
      '["Tu veux venir ? Y’a pas H.","J’ai activé y’a pas H.","Y’a pas H est une banque.","Y’a pas H = antivirus."]'::jsonb,
      0,
      'Formule d’accord / détente, pas un produit.',
      true,
      'live'::public.question_status,
      'ya_pas_h',
      'Pilot Y’a pas H — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'facile'::public.question_difficulty,
      '« J’ai la flemme de sortir. » Ça veut dire…',
      '["Pas envie / la paresse du moment","Une envie urgente de bouger","Un bug téléphone","Une panne de métro"]'::jsonb,
      0,
      'Avoir la flemme = ne pas avoir la motivation.',
      true,
      'live'::public.question_status,
      'flemme',
      'Pilot Flemme — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'moyen'::public.question_difficulty,
      'Quel message colle ?',
      '["Grosse flemme ce soir, on reporte.","J’ai installé flemme.","Flemme est un forfait.","Flemme = 5G."]'::jsonb,
      0,
      'État d’esprit, pas une appli.',
      true,
      'live'::public.question_status,
      'flemme',
      'Pilot Flemme — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'facile'::public.question_difficulty,
      '« Il a liké ? Osef. » Osef signifie…',
      '["On s’en fout / ça n’a aucune importance","On se fait une fête","On se connecte en 5G","On active le mode avion"]'::jsonb,
      0,
      'Osef = on s’en fout.',
      true,
      'live'::public.question_status,
      'osef',
      'Pilot Osef — authenticity scene check required before live.'
    ),
(
      'vocabulaire'::public.question_theme,
      'moyen'::public.question_difficulty,
      'Quel usage sonne juste ?',
      '["Qu’il soit vexé ou pas, osef.","J’ai activé osef dans les réglages.","Osef est une banque.","Osef = antivirus."]'::jsonb,
      0,
      'Marqueur d’indifférence, pas un outil.',
      true,
      'live'::public.question_status,
      'osef',
      'Pilot Osef — authenticity scene check required before live.'
    ),
(
      'trends_pop_culture'::public.question_theme,
      'moyen'::public.question_difficulty,
      'Ton ado répond « quoicoubeh » sans raison. Le plus juste, c’est…',
      '["Un mème / réplique absurde pour troller ou appartenir au groupe","Une question sur le Wi-Fi","Un code PIN","Une note de maths"]'::jsonb,
      0,
      'Comme six-seven : code de génération plus qu’une définition fixe.',
      true,
      'live'::public.question_status,
      'quoicoubeh',
      'Pilot Quoicoubeh — authenticity scene check required before live.'
    ),
(
      'trends_pop_culture'::public.question_theme,
      'facile'::public.question_difficulty,
      'Pourquoi « quoicoubeh » a agacé beaucoup d’adultes ?',
      '["Parce que c’est répété en boucle, souvent sans sens clair","Parce que c’est un virus","Parce que c’est une taxe","Parce que c’est un réglage iPhone"]'::jsonb,
      0,
      'Effet de mode FR (cour de récré) — idéal fil du jour.',
      true,
      'live'::public.question_status,
      'quoicoubeh',
      'Pilot Quoicoubeh — authenticity scene check required before live.'
    ),
(
      'relations_lifestyle'::public.question_theme,
      'moyen'::public.question_difficulty,
      '« C’est sa go. » Ici, go veut dire…',
      '["Sa petite amie / copine","Qu’il faut y aller tout de suite","Un bouton « démarrer »","Une appli de sport"]'::jsonb,
      0,
      'En FR ado, « go » / « gow » = petite amie (≠ l’anglais « go »).',
      true,
      'live'::public.question_status,
      'go',
      'Pilot Go — authenticity scene check required before live.'
    ),
(
      'relations_lifestyle'::public.question_theme,
      'facile'::public.question_difficulty,
      'Quel message sonne juste ?',
      '["Il est sorti avec sa go ce week-end.","J’ai activé go dans le Bluetooth.","Go est une banque.","Go = antivirus."]'::jsonb,
      0,
      'Relation amoureuse, pas un réglage.',
      true,
      'live'::public.question_status,
      'go',
      'Pilot Go — authenticity scene check required before live.'
    )
) AS v(theme, difficulty, question, choices, correct_index, explanation, is_active, status, concept_key, editor_notes)
WHERE NOT EXISTS (
  SELECT 1 FROM public.questions q WHERE q.question = v.question
)
RETURNING id, concept_key, left(question, 60) AS q;
