/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as ReglagesRouteImport } from './routes/reglages'
import { Route as QuestionDuJourRouteImport } from './routes/question-du-jour'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as NiveauxRouteImport } from './routes/niveaux'
import { Route as MarathonRouteImport } from './routes/marathon'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as DuelIndexRouteImport } from './routes/duel.index'
import { Route as QuizThemeRouteImport } from './routes/quiz.$theme'
import { Route as NiveauNRouteImport } from './routes/niveau.$n'
import { Route as DuelCodeRouteImport } from './routes/duel.$code'

const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglagesRoute = ReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionDuJourRoute = QuestionDuJourRouteImport.update({
  id: '/question-du-jour',
  path: '/question-du-jour',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const NiveauxRoute = NiveauxRouteImport.update({
  id: '/niveaux',
  path: '/niveaux',
  getParentRoute: () => rootRouteImport,
} as any)
const MarathonRoute = MarathonRouteImport.update({
  id: '/marathon',
  path: '/marathon',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelIndexRoute = DuelIndexRouteImport.update({
  id: '/duel/',
  path: '/duel/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizThemeRoute = QuizThemeRouteImport.update({
  id: '/quiz/$theme',
  path: '/quiz/$theme',
  getParentRoute: () => rootRouteImport,
} as any)
const NiveauNRoute = NiveauNRouteImport.update({
  id: '/niveau/$n',
  path: '/niveau/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelCodeRoute = DuelCodeRouteImport.update({
  id: '/duel/$code',
  path: '/duel/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connexion': typeof ConnexionRoute
  '/marathon': typeof MarathonRoute
  '/niveaux': typeof NiveauxRoute
  '/parcours': typeof ParcoursRoute
  '/question-du-jour': typeof QuestionDuJourRoute
  '/reglages': typeof ReglagesRoute
  '/statistiques': typeof StatistiquesRoute
  '/duel/$code': typeof DuelCodeRoute
  '/niveau/$n': typeof NiveauNRoute
  '/quiz/$theme': typeof QuizThemeRoute
  '/duel/': typeof DuelIndexRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connexion': typeof ConnexionRoute
  '/marathon': typeof MarathonRoute
  '/niveaux': typeof NiveauxRoute
  '/parcours': typeof ParcoursRoute
  '/question-du-jour': typeof QuestionDuJourRoute
  '/reglages': typeof ReglagesRoute
  '/statistiques': typeof StatistiquesRoute
  '/duel/$code': typeof DuelCodeRoute
  '/niveau/$n': typeof NiveauNRoute
  '/quiz/$theme': typeof QuizThemeRoute
  '/duel': typeof DuelIndexRoute
  '/quiz': typeof QuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connexion': typeof ConnexionRoute
  '/marathon': typeof MarathonRoute
  '/niveaux': typeof NiveauxRoute
  '/parcours': typeof ParcoursRoute
  '/question-du-jour': typeof QuestionDuJourRoute
  '/reglages': typeof ReglagesRoute
  '/statistiques': typeof StatistiquesRoute
  '/duel/$code': typeof DuelCodeRoute
  '/niveau/$n': typeof NiveauNRoute
  '/quiz/$theme': typeof QuizThemeRoute
  '/duel/': typeof DuelIndexRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/connexion'
    | '/marathon'
    | '/niveaux'
    | '/parcours'
    | '/question-du-jour'
    | '/reglages'
    | '/statistiques'
    | '/duel/$code'
    | '/niveau/$n'
    | '/quiz/$theme'
    | '/duel/'
    | '/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/connexion'
    | '/marathon'
    | '/niveaux'
    | '/parcours'
    | '/question-du-jour'
    | '/reglages'
    | '/statistiques'
    | '/duel/$code'
    | '/niveau/$n'
    | '/quiz/$theme'
    | '/duel'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/connexion'
    | '/marathon'
    | '/niveaux'
    | '/parcours'
    | '/question-du-jour'
    | '/reglages'
    | '/statistiques'
    | '/duel/$code'
    | '/niveau/$n'
    | '/quiz/$theme'
    | '/duel/'
    | '/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConnexionRoute: typeof ConnexionRoute
  MarathonRoute: typeof MarathonRoute
  NiveauxRoute: typeof NiveauxRoute
  ParcoursRoute: typeof ParcoursRoute
  QuestionDuJourRoute: typeof QuestionDuJourRoute
  ReglagesRoute: typeof ReglagesRoute
  StatistiquesRoute: typeof StatistiquesRoute
  DuelCodeRoute: typeof DuelCodeRoute
  NiveauNRoute: typeof NiveauNRoute
  QuizThemeRoute: typeof QuizThemeRoute
  DuelIndexRoute: typeof DuelIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglages': {
      id: '/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-du-jour': {
      id: '/question-du-jour'
      path: '/question-du-jour'
      fullPath: '/question-du-jour'
      preLoaderRoute: typeof QuestionDuJourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niveaux': {
      id: '/niveaux'
      path: '/niveaux'
      fullPath: '/niveaux'
      preLoaderRoute: typeof NiveauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marathon': {
      id: '/marathon'
      path: '/marathon'
      fullPath: '/marathon'
      preLoaderRoute: typeof MarathonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel/': {
      id: '/duel/'
      path: '/duel'
      fullPath: '/duel/'
      preLoaderRoute: typeof DuelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$theme': {
      id: '/quiz/$theme'
      path: '/quiz/$theme'
      fullPath: '/quiz/$theme'
      preLoaderRoute: typeof QuizThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niveau/$n': {
      id: '/niveau/$n'
      path: '/niveau/$n'
      fullPath: '/niveau/$n'
      preLoaderRoute: typeof NiveauNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel/$code': {
      id: '/duel/$code'
      path: '/duel/$code'
      fullPath: '/duel/$code'
      preLoaderRoute: typeof DuelCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConnexionRoute: ConnexionRoute,
  MarathonRoute: MarathonRoute,
  NiveauxRoute: NiveauxRoute,
  ParcoursRoute: ParcoursRoute,
  QuestionDuJourRoute: QuestionDuJourRoute,
  ReglagesRoute: ReglagesRoute,
  StatistiquesRoute: StatistiquesRoute,
  DuelCodeRoute: DuelCodeRoute,
  NiveauNRoute: NiveauNRoute,
  QuizThemeRoute: QuizThemeRoute,
  DuelIndexRoute: DuelIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
