// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * Canonical Supabase project root for createClient:
 * `https://<ref>.supabase.co/` (exactly one trailing slash, no `//`).
 * Strips `?query` / `#hash` so paths like `rest/v1` never get glued to the host (`…corest`).
 */
function normalizeSupabaseUrl(raw: string): string {
  const trimmed = raw.trim();
  const withoutQueryOrHash = trimmed.split(/[?#]/)[0]?.trim() ?? trimmed;
  const base = withoutQueryOrHash.replace(/\/+$/, "");
  if (!base) {
    throw new Error("Invalid VITE_SUPABASE_URL: empty after normalization.");
  }
  return `${base}/`;
}

/** Project URL — `import.meta.env.VITE_SUPABASE_URL` only (no hardcoded URLs). */
export function getSupabaseUrl(): string {
  const raw = import.meta.env.VITE_SUPABASE_URL;
  const s = typeof raw === "string" ? raw.trim() : "";
  if (!s) {
    throw new Error(
      "Missing VITE_SUPABASE_URL. Set it in .env so Vite injects it at build time.",
    );
  }
  return normalizeSupabaseUrl(s);
}

/** Publishable (anon) key — `import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY` only. */
export function getSupabasePublishableKey(): string {
  const raw = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  const s = typeof raw === "string" ? raw.trim() : "";
  if (!s) {
    throw new Error(
      "Missing VITE_SUPABASE_PUBLISHABLE_KEY. Set it in .env so Vite injects it at build time.",
    );
  }
  return s;
}

function createSupabaseClient() {
  return createClient<Database>(getSupabaseUrl(), getSupabasePublishableKey(), {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
